"use client";

import { useEffect, useState } from "react";
import { Form } from "@base-ui/react";
import { Check, Save, Settings } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { adminService, type AdminSettings } from "@/services/admin.service";

const fallback: AdminSettings = { storeName: "MyBag", supportEmail: "hello@mybag.id", currency: "IDR" };
export default function AdminSettingsPage() { const [settings, setSettings] = useState<AdminSettings>(fallback); const [saved, setSaved] = useState(false); const [error, setError] = useState<string | null>(null); useEffect(() => { void adminService.getSettings().then((result) => { if (result.error) setError(result.error.message); else if (result.data) setSettings(result.data); }); }, []); async function save() { const result = await adminService.updateSettings(settings); if (result.error) setError(result.error.message); else { setSettings(result.data ?? settings); setSaved(true); window.setTimeout(() => setSaved(false), 2200); } } return <div className="max-w-3xl space-y-7"><div><div className="mb-3 flex size-11 items-center justify-center bg-tertiary/10 text-tertiary"><Settings className="size-5" /></div><p className="mb-2 text-xs font-semibold uppercase tracking-[0.2em] text-tertiary">Workspace</p><h1 className="font-headline text-4xl font-bold">Settings</h1><p className="mt-2 text-sm text-zinc-500">Manage store details through the admin API.</p></div>{error && <p className="text-sm text-red-500">{error}</p>}<Form onFormSubmit={save} className="space-y-6 border border-zinc-200 bg-white p-6"><div className="grid gap-5 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="store-name">Store name</Label><Input id="store-name" value={settings.storeName} onChange={(event) => setSettings({ ...settings, storeName: event.target.value })} /></div><div className="space-y-2"><Label htmlFor="support-email">Support email</Label><Input id="support-email" type="email" value={settings.supportEmail} onChange={(event) => setSettings({ ...settings, supportEmail: event.target.value })} /></div></div><div className="space-y-2"><Label>Currency</Label><Select value={settings.currency} onValueChange={(value) => { if (value) setSettings({ ...settings, currency: value }); }}><SelectTrigger className="bg-white sm:w-56"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="IDR">Indonesian Rupiah (IDR)</SelectItem><SelectItem value="USD">US Dollar (USD)</SelectItem></SelectContent></Select></div><div className="flex justify-end border-t border-zinc-100 pt-5"><Button type="submit">{saved ? <Check /> : <Save />} {saved ? "Saved" : "Save changes"}</Button></div></Form></div>; }
