"use client";

import { Form } from "@base-ui/react";
import { ArrowLeft, Save } from "lucide-react";
import Link from "next/link";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { adminService } from "@/services/admin.service";

export function CustomerForm({ customerId }: { customerId: string }) { const [active, setActive] = useState("true"); const [name, setName] = useState("Loading customer..."); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false); useEffect(() => { void adminService.getCustomer(customerId).then((result) => { if (result.error) setError(result.error.message); else if (result.data) { setName(result.data.name ?? result.data.email); setActive(String(result.data.isActive !== false && result.data.status !== "Inactive")); } else setError("Customer not found."); }); }, [customerId]); async function submit() { setSaving(true); const result = await adminService.updateCustomerStatus(customerId, active === "true"); setSaving(false); if (result.error) setError(result.error.message); else window.location.href = "/admin/customers"; } return <div className="max-w-2xl space-y-7"><Button variant="ghost" nativeButton={false} render={<Link href="/admin/customers" />}><ArrowLeft /> Back to customers</Button><div><p className="mb-2 text-xs font-semibold uppercase tracking-[0.2em] text-tertiary">Relationships</p><h1 className="font-headline text-4xl font-bold">Edit customer</h1><p className="mt-2 text-sm text-zinc-500">Update account access for {name}.</p></div><Form onFormSubmit={submit} className="space-y-6 border border-zinc-200 bg-white p-6"><div className="space-y-2"><label className="text-sm font-medium">Account status</label><Select value={active} onValueChange={(value) => { if (value) setActive(value); }}><SelectTrigger className="bg-white"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="true">Active</SelectItem><SelectItem value="false">Inactive</SelectItem></SelectContent></Select></div>{error && <p className="text-sm text-red-500">{error}</p>}<div className="flex justify-end"><Button type="submit" disabled={saving}>{saving ? "Saving..." : <><Save /> Save customer</>}</Button></div></Form></div>; }
