"use client";

import { Form } from "@base-ui/react";
import { ArrowLeft, Save } from "lucide-react";
import Link from "next/link";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { adminService, type AdminDiscount } from "@/services/admin.service";

export function DiscountForm({ discountId }: { discountId?: string }) {
  const [discount, setDiscount] = useState<AdminDiscount | null>(null); const [name, setName] = useState(""); const [code, setCode] = useState(""); const [type, setType] = useState<"percentage" | "fixed">("percentage"); const [value, setValue] = useState(""); const [endsAt, setEndsAt] = useState(""); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  useEffect(() => { if (!discountId) return; void adminService.getDiscount(discountId).then((result) => { if (result.error) setError(result.error.message); else if (result.data) { const item = result.data; setDiscount(item); setName(item.name); setCode(item.code); setType(item.type === "fixed" || item.type === "Fixed amount" ? "fixed" : "percentage"); setValue(String(item.value).replace(/[^0-9.]/g, "")); setEndsAt(item.endsAt ?? item.ends ?? ""); } else setError("Discount not found."); }); }, [discountId]);
  async function submit() { if (!name.trim() || !code.trim() || !value) { setError("Name, code, and value are required."); return; } setSaving(true); setError(null); const payload = { name: name.trim(), code: code.trim().toUpperCase(), type, value: Number(value), endsAt, isActive: discount?.status === "active" || discount?.status === "Active" }; const result = discountId ? await adminService.updateDiscount(discountId, payload) : await adminService.createDiscount(payload); setSaving(false); if (result.error) setError(result.error.message); else window.location.href = "/admin/discounts"; }
  return <div className="max-w-3xl space-y-7"><Button variant="ghost" nativeButton={false} render={<Link href="/admin/discounts" />}><ArrowLeft /> Back to discounts</Button><div><p className="mb-2 text-xs font-semibold uppercase tracking-[0.2em] text-tertiary">Pricing</p><h1 className="font-headline text-4xl font-bold">{discountId ? "Edit discount" : "Create discount"}</h1><p className="mt-2 text-sm text-zinc-500">{discountId ? "Update campaign rules and timing." : "Create a promotion for your customers."}</p></div><Form onFormSubmit={submit} className="grid gap-5 border border-zinc-200 bg-white p-6 sm:grid-cols-2"><div className="space-y-2"><Label htmlFor="discount-name">Campaign name</Label><Input id="discount-name" value={name} onChange={(event) => setName(event.target.value)} placeholder="Independence Week" /></div><div className="space-y-2"><Label htmlFor="discount-code">Promo code</Label><Input id="discount-code" value={code} onChange={(event) => setCode(event.target.value)} placeholder="MERDEKA15" /></div><div className="space-y-2"><Label>Discount type</Label><Select value={type} onValueChange={(value) => { if (value) setType(value as "percentage" | "fixed"); }}><SelectTrigger className="bg-white"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="percentage">Percentage</SelectItem><SelectItem value="fixed">Fixed amount</SelectItem></SelectContent></Select></div><div className="space-y-2"><Label htmlFor="discount-value">Value</Label><Input id="discount-value" type="number" min="0" value={value} onChange={(event) => setValue(event.target.value)} placeholder={type === "percentage" ? "15" : "100000"} /></div><div className="space-y-2 sm:col-span-2"><Label htmlFor="discount-ends">Ends at</Label><Input id="discount-ends" type="date" value={endsAt} onChange={(event) => setEndsAt(event.target.value)} /></div>{error && <p className="text-sm text-red-500 sm:col-span-2">{error}</p>}<div className="flex justify-end sm:col-span-2"><Button type="submit" disabled={saving}>{saving ? "Saving..." : <><Save /> {discountId ? "Save discount" : "Create discount"}</>}</Button></div></Form></div>;
}
