"use client";

import { useEffect, useState } from "react";
import { ReceiptText } from "lucide-react";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { adminService, type AdminOrder } from "@/services/admin.service";

const statuses = ["pending", "paid", "shipped", "completed", "cancelled"];
export default function AdminOrdersPage() { const [orders, setOrders] = useState<AdminOrder[]>([]); const [filter, setFilter] = useState("all"); const [error, setError] = useState<string | null>(null); useEffect(() => { void adminService.listOrders({ status: filter === "all" ? undefined : filter }).then((result) => { if (result.error) setError(result.error.message); else setOrders(result.data ?? []); }); }, [filter]); async function updateStatus(id: string, status: string) { const result = await adminService.updateOrderStatus(id, status); if (result.error) setError(result.error.message); else setOrders((current) => current.map((order) => order.id === id ? { ...order, status } : order)); } return <div className="space-y-7"><div><div className="mb-3 flex size-11 items-center justify-center bg-tertiary/10 text-tertiary"><ReceiptText className="size-5" /></div><p className="mb-2 text-xs font-semibold uppercase tracking-[0.2em] text-tertiary">Fulfilment</p><h1 className="font-headline text-4xl font-bold">Orders</h1><p className="mt-2 text-sm text-zinc-500">Review and update orders through the admin API.</p></div><Select value={filter} onValueChange={(value) => { if (value) setFilter(value); }}><SelectTrigger className="w-44 bg-white"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">All statuses</SelectItem>{statuses.map((status) => <SelectItem key={status} value={status}>{status}</SelectItem>)}</SelectContent></Select>{error && <p className="text-sm text-red-500">{error}</p>}<div className="overflow-hidden border border-zinc-200 bg-white"><Table><TableHeader><TableRow><TableHead>Order</TableHead><TableHead>Customer</TableHead><TableHead>Total</TableHead><TableHead>Status</TableHead><TableHead>Date</TableHead></TableRow></TableHeader><TableBody>{orders.map((order) => <TableRow key={order.id}><TableCell className="font-mono text-xs">{order.id}</TableCell><TableCell>{order.customer ?? order.user_id ?? "-"}</TableCell><TableCell>{order.total}</TableCell><TableCell><Select value={order.status} onValueChange={(value) => { if (value) void updateStatus(order.id, value); }}><SelectTrigger className="h-8 w-32 bg-white text-xs"><SelectValue /></SelectTrigger><SelectContent>{statuses.map((status) => <SelectItem key={status} value={status}>{status}</SelectItem>)}</SelectContent></Select></TableCell><TableCell className="text-zinc-500">{order.created_at ?? order.date ?? "-"}</TableCell></TableRow>)}</TableBody></Table></div></div>; }
